import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Mark John Jopia
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_register = new javax.swing.JLabel();
        jLabel_remail = new javax.swing.JLabel();
        jLabel_rpassword = new javax.swing.JLabel();
        jLabel_Login_link = new javax.swing.JLabel();
        textField_remail = new java.awt.TextField();
        passwordField_rpassword = new javax.swing.JPasswordField();
        button_register = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_register.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_register.setText("Register");

        jLabel_remail.setText("Email");

        jLabel_rpassword.setText("Password");

        jLabel_Login_link.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Login_link.setText("Already have an account? Click here to login.");
        jLabel_Login_link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Login_linkMouseClicked(evt);
            }
        });

        textField_remail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_remailActionPerformed(evt);
            }
        });

        passwordField_rpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField_rpasswordActionPerformed(evt);
            }
        });

        button_register.setLabel("Register");
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Login_link, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_rpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel_remail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_register, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(textField_remail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField_rpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel_register)
                .addGap(18, 18, 18)
                .addComponent(jLabel_remail)
                .addGap(1, 1, 1)
                .addComponent(textField_remail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_rpassword)
                .addGap(1, 1, 1)
                .addComponent(passwordField_rpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Login_link, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Login_linkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Login_linkMouseClicked
        
        // Create an instance of the LoginForm
        LoginForm loginForm = new LoginForm();
        
        // Make the LoginForm visible
        loginForm.setVisible(true);
        
        // Close the current form
        this.dispose();
    }//GEN-LAST:event_jLabel_Login_linkMouseClicked

    private void textField_remailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_remailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_remailActionPerformed

    private void passwordField_rpasswordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_rpasswordActionPerformed

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {
        // Get the email and password from the text fields
        String email = textField_remail.getText();
        String password = passwordField_rpassword.getText();

        // Validate that the fields are not empty
        if (!email.isEmpty() && !password.isEmpty()) {
            // Call the FirebaseAuth.registerUser method
            JSONObject response = FirebaseAuth.registerUser(email, password);
            if (response != null) {
                // Registration successful
                JOptionPane.showMessageDialog(this, "Registration successful!");

                // Send verification email
                String idToken = response.getString("idToken"); // Get the ID token from the response
                boolean emailSent = FirebaseAuth.sendVerificationEmail(idToken);
                if (emailSent) {
                    JOptionPane.showMessageDialog(this, "Verification email sent. Please check your inbox.");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to send verification email. Please try again.");
                }

                // Open the login form after successful registration
                LoginForm loginForm = new LoginForm();
                loginForm.setVisible(true);
                this.dispose(); // Close the current registration form
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed. Please try again.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Email and password cannot be empty!");
        }
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_register;
    private javax.swing.JLabel jLabel_Login_link;
    private javax.swing.JLabel jLabel_register;
    private javax.swing.JLabel jLabel_remail;
    private javax.swing.JLabel jLabel_rpassword;
    private java.awt.TextField textField_remail;
    private javax.swing.JPasswordField passwordField_rpassword;
    // End of variables declaration//GEN-END:variables
}
